
[tool.bumpversion]
# NOTE:
#   This is the bump definition for the 'stac-model' package.
#   For the MLM specification, refer to the main 'pyproject.toml'.
#   they are actually intented for versioning the MLM specification itself.
#   To version 'stac-model', use the 'bump-my-version bump' operation with this file.
#   See also https://github.com/stac-extensions/mlm/blob/main/CONTRIBUTING.md#building-and-releasing
current_version = "0.3.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = true
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "stac-model-v{new_version}"
tag_message = "Bump version: stac-model {current_version} → {new_version}"
allow_dirty = false
commit = true
commit_args = "--no-verify"
message = "Bump version: stac-model {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "uv.lock"
search = """
name = "stac-model"
version = "{current_version}"
"""
replace = """
name = "stac-model"
version = "{new_version}"
"""

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = """
name = "stac-model"
version = "{current_version}"
"""
replace = """
name = "stac-model"
version = "{new_version}"
"""
