name: Check Python Linting and Tests

on: [push, pull_request]

jobs:
  stac-model:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      COVERAGE_FILE: .coverage.${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: make setup

    - name: Set up cache
      uses: actions/cache@v4.3.0
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('uv.lock') }}

    - name: Install dependencies
      run: make install-dev
      if: ${{ matrix.python-version == '3.10' }}

    - name: Install dependencies with extras
      run: make install-dev-extras
      if: ${{ matrix.python-version != '3.10' }}

    - name: Display Packages
      run: pip list

    - name: Run checks
      if: ${{ matrix.python-version != '3.10' }}
      run: make lint-all

    - name: Run tests
      run: |
        make test
